// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVJuBSgd-n_8NXVwywkOwhanqHz6RbIU',
    appId: '1:633652693313:web:193fa3d63f382a1829f9c0',
    messagingSenderId: '633652693313',
    projectId: 'minimal-social-app-flutter',
    authDomain: 'minimal-social-app-flutter.firebaseapp.com',
    storageBucket: 'minimal-social-app-flutter.appspot.com',
    measurementId: 'G-BHMHW9X18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uFNRLm2IZDkSqHcVPyxpOGZYH2n7Kz8',
    appId: '1:633652693313:android:079dc9c3b4942f0229f9c0',
    messagingSenderId: '633652693313',
    projectId: 'minimal-social-app-flutter',
    storageBucket: 'minimal-social-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZho1RoEjt0XOjs7lgeRz9hbeKrkX9Zmw',
    appId: '1:633652693313:ios:06a06f0d65e1e12f29f9c0',
    messagingSenderId: '633652693313',
    projectId: 'minimal-social-app-flutter',
    storageBucket: 'minimal-social-app-flutter.appspot.com',
    iosBundleId: 'com.example.minimalsocialapp',
  );
}
